import type { Product, CategoryInfo } from './types';

const img = {
  hairClip: 'https://images.pexels.com/photos/18031831/pexels-photo-18031831.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  hairAccessory: 'https://images.pexels.com/photos/13929358/pexels-photo-13929358.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  scrunchie: 'https://images.pexels.com/photos/30284737/pexels-photo-30284737.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  scrunchieWhite: 'https://images.pexels.com/photos/37401207/pexels-photo-37401207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  keychain1: 'https://images.pexels.com/photos/37129474/pexels-photo-37129474.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  keychain2: 'https://images.pexels.com/photos/38634277/pexels-photo-38634277.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  flower1: 'https://images.pexels.com/photos/20269075/pexels-photo-20269075.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  flower2: 'https://images.pexels.com/photos/29753249/pexels-photo-29753249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  flower3: 'https://images.pexels.com/photos/13574113/pexels-photo-13574113.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  flower4: 'https://images.pexels.com/photos/17864125/pexels-photo-17864125.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  flowerPots: 'https://images.pexels.com/photos/29753247/pexels-photo-29753247.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  flowerArt: 'https://images.pexels.com/photos/29021043/pexels-photo-29021043.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  flowerPots2: 'https://images.pexels.com/photos/29753248/pexels-photo-29753248.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  sunflower: 'https://images.pexels.com/photos/18692008/pexels-photo-18692008.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bouquet1: 'https://images.pexels.com/photos/15469188/pexels-photo-15469188.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bouquet2: 'https://images.pexels.com/photos/28450065/pexels-photo-28450065.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bouquet3: 'https://images.pexels.com/photos/34767997/pexels-photo-34767997.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bouquet4: 'https://images.pexels.com/photos/29753251/pexels-photo-29753251.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  bouquet5: 'https://images.pexels.com/photos/39412616/pexels-photo-39412616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi1: 'https://images.pexels.com/photos/37553410/pexels-photo-37553410.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi2: 'https://images.pexels.com/photos/38724016/pexels-photo-38724016.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi3: 'https://images.pexels.com/photos/33480808/pexels-photo-33480808.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi4: 'https://images.pexels.com/photos/38718819/pexels-photo-38718819.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi5: 'https://images.pexels.com/photos/38914365/pexels-photo-38914365.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi6: 'https://images.pexels.com/photos/33481692/pexels-photo-33481692.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi7: 'https://images.pexels.com/photos/10585164/pexels-photo-10585164.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  amigurumi8: 'https://images.pexels.com/photos/38745727/pexels-photo-38745727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  yarn1: 'https://images.pexels.com/photos/19479499/pexels-photo-19479499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  yarn2: 'https://images.pexels.com/photos/5788379/pexels-photo-5788379.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  yarn3: 'https://images.pexels.com/photos/5602983/pexels-photo-5602983.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  cozy: 'https://images.pexels.com/photos/29970643/pexels-photo-29970643.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  decor1: 'https://images.pexels.com/photos/27864328/pexels-photo-27864328.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  decor2: 'https://images.pexels.com/photos/10464182/pexels-photo-10464182.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  decor3: 'https://images.pexels.com/photos/6654123/pexels-photo-6654123.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  decor4: 'https://images.pexels.com/photos/15130358/pexels-photo-15130358.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  decor5: 'https://images.pexels.com/photos/11608137/pexels-photo-11608137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  craft1: 'https://images.pexels.com/photos/19684866/pexels-photo-19684866.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  craft2: 'https://images.pexels.com/photos/7585259/pexels-photo-7585259.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  heart: 'https://images.pexels.com/photos/36595917/pexels-photo-36595917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
};

export const products: Product[] = [
  // ==================== HAIR ACCESSORIES ====================
  {
    id: 'hair-rubber-band-pack3',
    name: 'Hair Rubber Band',
    category: 'Hair Accessories',
    price: 450,
    description: 'Pack of 3 handmade crochet hair rubber bands. Soft, stretchy and gentle on hair. Perfect for everyday use.',
    shortDetail: 'Pack of 3',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'rubber', 'band', 'pack', 'crochet'],
    pack: 'Pack of 3',
  },
  {
    id: 'hair-rubber-band-rose-pack2',
    name: 'Hair Rubber Band Rose',
    category: 'Hair Accessories',
    price: 300,
    description: 'Pack of 2 beautiful rose-design crochet hair rubber bands. Elegant and feminine.',
    shortDetail: 'Pack of 2',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'rubber', 'band', 'rose', 'pack'],
    pack: 'Pack of 2',
  },
  {
    id: 'roses-3-combo',
    name: 'Roses',
    category: 'Hair Accessories',
    price: 350,
    description: 'A combo of 3 crochet rose hair accessories. Beautifully crafted roses in a set.',
    shortDetail: '3 combo',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'roses', 'combo', 'hair', 'flower'],
    pack: '3 combo',
  },
  {
    id: 'hair-pin-3-colours',
    name: 'Hair Pin',
    category: 'Hair Accessories',
    price: 150,
    description: 'Set of 3 hair pins in different colours. Each priced individually at ₹150.',
    shortDetail: '3 different colours / each',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'pin', 'colours', 'set'],
  },
  {
    id: 'hair-clip-pack3',
    name: 'Hair Clip',
    category: 'Hair Accessories',
    price: 300,
    description: 'Pack of 3 handmade crochet hair clips. Cute and comfortable for daily wear.',
    shortDetail: 'Pack of 3',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'clip', 'pack', 'crochet'],
    pack: 'Pack of 3',
  },
  {
    id: 'hair-clutcher-2',
    name: 'Hair Clutcher',
    category: 'Hair Accessories',
    price: 150,
    description: 'Set of 2 crochet hair clutcher clips. Holds hair securely with a handmade touch.',
    shortDetail: '2 qty',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'clutcher', 'clip', 'pack'],
    pack: '2 qty',
  },
  {
    id: 'hair-clip-250',
    name: 'Hair Clip',
    category: 'Hair Accessories',
    price: 250,
    description: 'A beautiful handmade crochet hair clip. Perfect for adding a cute touch to any hairstyle.',
    shortDetail: 'Handmade crochet clip',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'clip', 'crochet', 'handmade'],
  },
  {
    id: 'cute-hair-clip-120',
    name: 'Cute Hair Clip',
    category: 'Hair Accessories',
    price: 120,
    originalPrice: 150,
    description: 'An adorable handmade crochet hair clip. Perfect for kids and adults alike.',
    shortDetail: 'Adorable crochet clip',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['cute', 'hair', 'clip', 'crochet'],
  },
  {
    id: 'cute-hair-clip-bow',
    name: 'Cute Hair Clip Bow',
    category: 'Hair Accessories',
    price: 200,
    originalPrice: 250,
    description: 'A sweet bow-design crochet hair clip. Adds a charming touch to any outfit.',
    shortDetail: 'Bow design clip',
    image: img.hairAccessory,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['cute', 'hair', 'clip', 'bow', 'crochet'],
  },
  {
    id: 'cute-hair-clip-300',
    name: 'Cute Hair Clip',
    category: 'Hair Accessories',
    price: 300,
    originalPrice: 350,
    description: 'A lovely crochet hair clip available in multiple colours. Choose your favourite!',
    shortDetail: 'Colour available',
    image: img.hairClip,
    featured: false,
    customizable: true,
    variants: ['Red', 'Pink', 'Yellow', 'Blue', 'Green', 'Other'],
    availability: 'in-stock',
    keywords: ['cute', 'hair', 'clip', 'colour', 'crochet'],
  },
  {
    id: 'cute-hair-bands',
    name: 'Cute Hair Bands',
    category: 'Hair Accessories',
    price: 200,
    originalPrice: 300,
    description: 'Beautiful crochet hair bands in different colours. Comfortable and stylish.',
    shortDetail: 'Different colours available',
    image: img.hairAccessory,
    featured: false,
    customizable: true,
    variants: ['Red', 'Pink', 'Yellow', 'Blue', 'Green', 'Other'],
    availability: 'in-stock',
    keywords: ['cute', 'hair', 'bands', 'colours', 'crochet'],
  },
  {
    id: 'cherry-rubber-band',
    name: 'Cherry Rubber Band',
    category: 'Hair Accessories',
    price: 200,
    originalPrice: 300,
    description: 'Cute cherry-design crochet rubber band. A fun and playful hair accessory.',
    shortDetail: 'Cherry design',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['cherry', 'rubber', 'band', 'hair', 'cute'],
  },
  {
    id: 'rose-hair-rubber-band',
    name: 'Rose Hair Rubber Band',
    category: 'Hair Accessories',
    price: 150,
    description: 'A delicate rose-design crochet hair rubber band. Elegant and affordable.',
    shortDetail: 'Rose design',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'hair', 'rubber', 'band', 'flower'],
  },
  {
    id: 'rose-hair-pin-juda',
    name: 'Rose Hair Pin for Juda',
    category: 'Hair Accessories',
    price: 300,
    description: 'A beautiful crochet rose hair pin designed specifically for juda (bun) hairstyles. Elegant and secure.',
    shortDetail: 'For Juda / Bun hairstyle',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'hair', 'pin', 'juda', 'bun', 'flower'],
  },
  {
    id: 'cherry-hair-clip',
    name: 'Cherry Hair Clip',
    category: 'Hair Accessories',
    price: 200,
    originalPrice: 250,
    description: 'An adorable cherry-design crochet hair clip. Sweet and playful for everyday wear.',
    shortDetail: 'Cherry design',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['cherry', 'hair', 'clip', 'cute', 'crochet'],
  },
  {
    id: 'rose-hair-pin-300',
    name: 'Rose Hair Pin',
    category: 'Hair Accessories',
    price: 300,
    originalPrice: 350,
    description: 'A delicate crochet rose hair pin. Adds a beautiful floral touch to any hairstyle.',
    shortDetail: 'Rose design pin',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'hair', 'pin', 'flower', 'crochet'],
  },
  {
    id: 'hair-pin-custom-color',
    name: 'Hair Pin',
    category: 'Hair Accessories',
    price: 150,
    originalPrice: 200,
    description: 'A handmade crochet hair pin with customisable colour. Choose your favourite shade!',
    shortDetail: 'Colour can be customized',
    image: img.hairClip,
    featured: false,
    customizable: true,
    variants: ['Red', 'Pink', 'Yellow', 'Blue', 'Green', 'Other'],
    availability: 'custom',
    keywords: ['hair', 'pin', 'colour', 'custom', 'crochet'],
  },
  {
    id: 'rose-hair-clip-white',
    name: 'Rose Hair Clip with White',
    category: 'Hair Accessories',
    price: 120,
    originalPrice: 150,
    description: 'A beautiful rose hair clip with white detailing. Elegant and feminine.',
    shortDetail: 'Rose with white detail',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'hair', 'clip', 'white', 'flower'],
  },
  {
    id: 'hair-tie',
    name: 'Hair Tie',
    category: 'Hair Accessories',
    price: 200,
    description: 'A handmade crochet hair tie. Soft, comfortable and perfect for everyday use.',
    shortDetail: 'Crochet hair tie',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'tie', 'crochet', 'handmade'],
  },
  {
    id: 'flower-hair-clutcher',
    name: 'Flower Hair Clutcher',
    category: 'Hair Accessories',
    price: 200,
    description: 'A beautiful crochet flower hair clutcher. Colour can be customized to match your style.',
    shortDetail: 'Colour can be customized',
    image: img.hairAccessory,
    featured: false,
    customizable: true,
    variants: ['Red', 'Pink', 'Yellow', 'Blue', 'Green', 'White', 'Other'],
    availability: 'custom',
    keywords: ['flower', 'hair', 'clutcher', 'colour', 'custom'],
  },
  {
    id: 'hair-clutcher-daisy',
    name: 'Hair Clutcher Daisy',
    category: 'Hair Accessories',
    price: 250,
    description: 'A cheerful daisy-design crochet hair clutcher. Bright and beautiful.',
    shortDetail: 'Daisy design',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'clutcher', 'daisy', 'flower', 'crochet'],
  },
  {
    id: 'sunflower-rubber-band',
    name: 'Sunflower Rubber Band',
    category: 'Hair Accessories',
    price: 200,
    originalPrice: 300,
    description: 'Pack of 2 sunflower-design crochet rubber bands. Bright and cheerful.',
    shortDetail: 'Pack of 2',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['sunflower', 'rubber', 'band', 'hair', 'pack', 'flower'],
    pack: 'Pack of 2',
  },
  {
    id: 'mini-hair-scrunchies',
    name: 'Mini Hair Scrunchies',
    category: 'Hair Accessories',
    price: 500,
    originalPrice: 600,
    description: 'Pack of 3 mini crochet hair scrunchies. Soft, cute and perfect for ponytails.',
    shortDetail: 'Pack of 3',
    image: img.scrunchie,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['mini', 'hair', 'scrunchie', 'scrunchies', 'pack', 'crochet'],
    pack: 'Pack of 3',
  },
  {
    id: 'evil-eye-scrunchie',
    name: 'Evil Eye Scrunchie',
    category: 'Hair Accessories',
    price: 300,
    originalPrice: 400,
    description: 'An evil eye design crochet scrunchie. Protective and stylish!',
    shortDetail: 'Evil eye design',
    image: img.scrunchie,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['evil', 'eye', 'scrunchie', 'hair', 'nazar'],
  },
  {
    id: 'rose-hair-rubber-band-pack4',
    name: 'Rose Hair Rubber Band',
    category: 'Hair Accessories',
    price: 450,
    description: 'Pack of 4 rose-design crochet hair rubber bands. Beautiful and practical.',
    shortDetail: 'Pack of 4',
    image: img.hairClip,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'hair', 'rubber', 'band', 'pack', 'flower'],
    pack: 'Pack of 4',
  },
  {
    id: 'hair-rubber-band-pack6',
    name: 'Hair Rubber Band',
    category: 'Hair Accessories',
    price: 350,
    description: 'Pack of 6 handmade crochet hair rubber bands. Great value and variety.',
    shortDetail: 'Pack of 6',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'rubber', 'band', 'pack', 'crochet'],
    pack: 'Pack of 6',
  },
  {
    id: 'hair-scrunchies-pack3',
    name: 'Hair Scrunchies',
    category: 'Hair Accessories',
    price: 500,
    originalPrice: 600,
    description: 'Pack of 3 beautiful crochet hair scrunchies. Soft, stylish and gentle on hair.',
    shortDetail: 'Pack of 3',
    image: img.scrunchieWhite,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['hair', 'scrunchie', 'scrunchies', 'pack', 'crochet'],
    pack: 'Pack of 3',
  },

  // ==================== KEYCHAINS & CHARMS ====================
  {
    id: 'keychain-daisy',
    name: 'Keychain Daisy',
    category: 'Keychains & Charms',
    price: 150,
    description: 'A cute daisy-design crochet keychain. Brighten up your keys or bag.',
    shortDetail: 'Daisy design',
    image: img.keychain1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['keychain', 'daisy', 'flower', 'crochet'],
  },
  {
    id: 'heart-keychain',
    name: 'Heart Keychain',
    category: 'Keychains & Charms',
    price: 150,
    description: 'A sweet crochet heart keychain. Colour can be customized to your preference.',
    shortDetail: 'Colour can be customized',
    image: img.heart,
    featured: false,
    customizable: true,
    variants: ['Red', 'Pink', 'Yellow', 'Blue', 'Green', 'White', 'Other'],
    availability: 'custom',
    keywords: ['heart', 'keychain', 'colour', 'custom', 'crochet'],
  },
  {
    id: 'keychain-butterfly',
    name: 'Keychain Butterfly',
    category: 'Keychains & Charms',
    price: 250,
    originalPrice: 300,
    description: 'A beautiful butterfly-design crochet keychain. Delicate and colourful.',
    shortDetail: 'Butterfly design',
    image: img.keychain1,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['keychain', 'butterfly', 'crochet', 'charm'],
  },
  {
    id: 'alphabet-keychain',
    name: 'Alphabet Keychain A-Z',
    category: 'Keychains & Charms',
    price: 200,
    description: 'Personalised alphabet crochet keychains from A to Z. Pick your initial!',
    shortDetail: 'A-Z available',
    image: img.keychain2,
    featured: true,
    customizable: true,
    variants: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
    availability: 'made-to-order',
    keywords: ['alphabet', 'keychain', 'letter', 'personalized', 'custom', 'A-Z'],
  },
  {
    id: 'bow-keychain',
    name: 'Bow Keychain',
    category: 'Keychains & Charms',
    price: 150,
    originalPrice: 200,
    description: 'A cute bow-design crochet keychain. Sweet and feminine.',
    shortDetail: 'Bow design',
    image: img.keychain1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['bow', 'keychain', 'crochet', 'cute'],
  },
  {
    id: 'small-daisy-keychain',
    name: 'Small Daisy Keychain',
    category: 'Keychains & Charms',
    price: 100,
    description: 'A tiny daisy crochet keychain. Perfect as a bag charm or gift accessory.',
    shortDetail: 'Mini daisy charm',
    image: img.keychain1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['small', 'daisy', 'keychain', 'mini', 'charm', 'flower'],
  },
  {
    id: 'rose-bouquet-keychain',
    name: 'Rose Bouquet Keychain',
    category: 'Keychains & Charms',
    price: 300,
    originalPrice: 400,
    description: 'A miniature rose bouquet crochet keychain. A tiny bunch of beautiful roses for your keys.',
    shortDetail: 'Mini rose bouquet',
    image: img.keychain2,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'bouquet', 'keychain', 'flower', 'mini'],
  },
  {
    id: 'couple-spider-keychain',
    name: 'Cute Couple Spider Keychain',
    category: 'Keychains & Charms',
    price: 500,
    originalPrice: 600,
    description: 'An adorable couple spider crochet keychain set. Perfect for couples!',
    shortDetail: 'Couple spider set',
    image: img.keychain2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['couple', 'spider', 'keychain', 'cute', 'set', 'pair'],
  },
  {
    id: 'honeybee-charm',
    name: 'Cute Honeybee Charm',
    category: 'Keychains & Charms',
    price: 250,
    description: 'A sweet honeybee crochet charm. Buzzing with cuteness!',
    shortDetail: 'Honeybee charm',
    image: img.keychain1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['honeybee', 'bee', 'charm', 'cute', 'crochet'],
  },
  {
    id: 'mickey-mouse-keychain',
    name: 'Micky Mouse Keychain',
    category: 'Keychains & Charms',
    price: 200,
    originalPrice: 250,
    description: 'A cute Micky Mouse crochet keychain. Perfect for Disney lovers!',
    shortDetail: 'Micky Mouse design',
    image: img.keychain2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['mickey', 'mouse', 'keychain', 'disney', 'cute', 'character'],
  },
  {
    id: 'puff-red-heart-keychain',
    name: 'Puff Red Heart Keychain',
    category: 'Keychains & Charms',
    price: 200,
    originalPrice: 250,
    description: 'A puffy red heart crochet keychain. Soft, squishy and adorable.',
    shortDetail: 'Puffy red heart',
    image: img.heart,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['puff', 'red', 'heart', 'keychain', 'puffy', 'love'],
  },
  {
    id: 'bow-keychain-white',
    name: 'Bow Keychain with White',
    category: 'Keychains & Charms',
    price: 300,
    originalPrice: 400,
    description: 'A beautiful bow keychain with white detailing. Available in 2 colour combinations.',
    shortDetail: '2 colours available',
    image: img.keychain1,
    featured: false,
    customizable: true,
    variants: ['Pink & White', 'Blue & White', 'Other'],
    availability: 'in-stock',
    keywords: ['bow', 'keychain', 'white', 'colour', 'crochet'],
  },
  {
    id: 'nazaar-keychain',
    name: 'Nazaar Keychain',
    category: 'Keychains & Charms',
    price: 300,
    originalPrice: 450,
    description: 'A nazar (evil eye) amulet crochet keychain. Protective and beautiful.',
    shortDetail: 'Evil eye / Nazar design',
    image: img.keychain2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['nazaar', 'nazar', 'evil', 'eye', 'keychain', 'protection'],
  },
  {
    id: 'bouquet-keychain',
    name: 'Bouquet Keychain',
    category: 'Keychains & Charms',
    price: 250,
    description: 'A miniature bouquet crochet keychain. A tiny bunch of flowers for your keys.',
    shortDetail: 'Mini bouquet charm',
    image: img.keychain2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['bouquet', 'keychain', 'flower', 'mini', 'charm'],
  },
  {
    id: 'peacock-keychain',
    name: 'Peacock Keychain',
    category: 'Keychains & Charms',
    price: 300,
    originalPrice: 450,
    description: 'A stunning peacock-design crochet keychain. Colourful and eye-catching.',
    shortDetail: 'Peacock design',
    image: img.keychain1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['peacock', 'keychain', 'bird', 'colourful', 'crochet'],
  },
  {
    id: 'sunflower-keychain',
    name: 'Sunflower Keychain',
    category: 'Keychains & Charms',
    price: 150,
    originalPrice: 200,
    description: 'A bright sunflower-design crochet keychain. Cheerful and cute.',
    shortDetail: 'Sunflower design',
    image: img.keychain1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['sunflower', 'keychain', 'flower', 'bright', 'crochet'],
  },
  {
    id: 'cute-duck-keychain',
    name: 'Cute Duck Keychain',
    category: 'Keychains & Charms',
    price: 450,
    originalPrice: 500,
    description: 'An adorable duck crochet keychain. Quack quack! Perfect for animal lovers.',
    shortDetail: 'Cute duck design',
    image: img.amigurumi1,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['cute', 'duck', 'keychain', 'animal', 'yellow'],
  },
  {
    id: 'resin-keychain-az',
    name: 'Resin Keychain A-Z',
    category: 'Keychains & Charms',
    price: 250,
    description: 'Personalised resin keychains from A to Z. Pick your initial!',
    shortDetail: 'A-Z available',
    image: img.keychain2,
    featured: false,
    customizable: true,
    variants: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
    availability: 'made-to-order',
    keywords: ['resin', 'keychain', 'alphabet', 'letter', 'personalized', 'A-Z'],
  },
  {
    id: 'small-puffy-keychain',
    name: 'Small Puffy Keychain',
    category: 'Keychains & Charms',
    price: 100,
    description: 'A tiny puffy crochet keychain. Soft, squishy and adorable.',
    shortDetail: 'Mini puffy charm',
    image: img.keychain1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['small', 'puffy', 'keychain', 'mini', 'charm'],
  },
  {
    id: 'coffee-lover-keychain',
    name: 'Cute Coffee Lover Keychain',
    category: 'Keychains & Charms',
    price: 500,
    originalPrice: 600,
    description: 'A coffee cup design crochet keychain for coffee lovers! Cute and detailed.',
    shortDetail: 'Coffee cup design',
    image: img.keychain2,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['coffee', 'lover', 'keychain', 'cup', 'cute', 'crochet'],
  },
  {
    id: 'burger-keychain',
    name: 'Cute Burger Keychain',
    category: 'Keychains & Charms',
    price: 300,
    originalPrice: 350,
    description: 'An adorable burger-design crochet keychain. Fun and quirky!',
    shortDetail: 'Burger design',
    image: img.keychain2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['burger', 'keychain', 'food', 'cute', 'fun', 'crochet'],
  },
  {
    id: 'rose-heart-keychain',
    name: 'Rose and Small Heart Keychain',
    category: 'Keychains & Charms',
    price: 250,
    originalPrice: 300,
    description: 'A beautiful keychain featuring a crochet rose and small heart. Romantic and sweet.',
    shortDetail: 'Rose + heart design',
    image: img.heart,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['rose', 'heart', 'keychain', 'love', 'flower'],
  },

  // ==================== CROCHET FLOWERS / DECOR ====================
  {
    id: 'tulip-car-hanging',
    name: 'Tulip Car Hanging',
    category: 'Home & Car Décor',
    price: 350,
    originalPrice: 500,
    description: 'A beautiful tulip crochet car hanging. Brighten up your car interior with handmade charm.',
    shortDetail: 'Car hanging decor',
    image: img.decor1,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['tulip', 'car', 'hanging', 'decor', 'flower', 'crochet'],
  },
  {
    id: 'duck-hanging',
    name: 'Duck Hanging',
    category: 'Home & Car Décor',
    price: 750,
    originalPrice: 800,
    description: 'A cute duck crochet hanging decoration. Perfect for cars or room decor.',
    shortDetail: 'Duck hanging decor',
    image: img.amigurumi1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['duck', 'hanging', 'car', 'decor', 'cute', 'crochet'],
  },
  {
    id: 'evil-eye-hanging',
    name: 'Evil Eye Hanging',
    category: 'Home & Car Décor',
    price: 350,
    originalPrice: 400,
    description: 'An evil eye (nazar) crochet hanging decoration. Available in 3 colours. Protective and beautiful.',
    shortDetail: 'Available in 3 colours',
    image: img.decor1,
    featured: false,
    customizable: true,
    variants: ['Blue', 'White', 'Mixed', 'Other'],
    availability: 'in-stock',
    keywords: ['evil', 'eye', 'hanging', 'nazar', 'car', 'decor', 'colour'],
  },
  {
    id: 'watermelon-accessory',
    name: 'Watermelon Hair Accessory',
    category: 'Crochet Flowers',
    price: 300,
    originalPrice: 350,
    description: 'A cute watermelon-design crochet hair/accessory item. Fresh and fun!',
    shortDetail: 'Watermelon design',
    image: img.hairAccessory,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['watermelon', 'hair', 'accessory', 'fruit', 'cute', 'crochet'],
  },
  {
    id: 'crochet-lavender-stick',
    name: 'Crochet Lavender Stick',
    category: 'Crochet Flowers',
    price: 300,
    originalPrice: 400,
    description: 'Pack of 2 crochet lavender sticks. Beautiful and fragrant-looking decorative flowers.',
    shortDetail: 'Pack of 2',
    image: img.flower2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['lavender', 'stick', 'flower', 'pack', 'purple', 'crochet'],
    pack: 'Pack of 2',
  },
  {
    id: 'crochet-tulip-flower',
    name: 'Crochet Tulip Flower',
    category: 'Crochet Flowers',
    price: 450,
    originalPrice: 500,
    description: 'A beautiful handmade crochet tulip flower. Elegant and long-lasting.',
    shortDetail: 'Single tulip flower',
    image: img.flower1,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['tulip', 'flower', 'crochet', 'handmade'],
  },
  {
    id: 'mini-sunflower',
    name: 'Small Mini Sunflower',
    category: 'Crochet Flowers',
    price: 150,
    originalPrice: 180,
    description: 'A mini crochet sunflower. Can be customized in rose or other colours as shown.',
    shortDetail: 'Customizable colour',
    image: img.sunflower,
    featured: false,
    customizable: true,
    variants: ['Yellow', 'Rose Pink', 'White', 'Orange', 'Other'],
    availability: 'custom',
    keywords: ['mini', 'small', 'sunflower', 'flower', 'custom', 'colour', 'crochet'],
  },
  {
    id: 'beautiful-sunflower',
    name: 'Beautiful Sunflower',
    category: 'Crochet Flowers',
    price: 800,
    originalPrice: 900,
    description: 'A large, beautiful handmade crochet sunflower. A stunning decorative piece.',
    shortDetail: 'Large sunflower',
    image: img.sunflower,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['beautiful', 'sunflower', 'large', 'flower', 'crochet', 'decor'],
  },
  {
    id: 'white-sunflower-curtains',
    name: 'White Sunflower Curtains',
    category: 'Home & Car Décor',
    price: 1500,
    originalPrice: 1800,
    description: '2 pairs of white sunflower crochet curtains. Beautiful handmade window decor.',
    shortDetail: '2 pairs',
    image: img.decor2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'made-to-order',
    keywords: ['white', 'sunflower', 'curtains', 'window', 'decor', 'pair'],
    pack: '2 pairs',
  },
  {
    id: 'sunflower-curtains',
    name: 'Sunflower Curtains',
    category: 'Home & Car Décor',
    price: 4500,
    originalPrice: 5000,
    description: 'Beautiful sunflower crochet curtains. Colour can be customized to match your decor.',
    shortDetail: 'Colour can be customized',
    image: img.decor2,
    featured: false,
    customizable: true,
    variants: ['Yellow', 'White', 'Pink', 'Blue', 'Green', 'Other'],
    availability: 'made-to-order',
    keywords: ['sunflower', 'curtains', 'window', 'decor', 'colour', 'custom'],
  },
  {
    id: 'beach-vibes-crochet',
    name: 'Beautiful Beach Vibes Crochet Item',
    category: 'Home & Car Décor',
    price: 850,
    originalPrice: 1000,
    description: 'A beautiful beach vibes crochet decorative item. Options available.',
    shortDetail: 'Options available',
    image: img.decor3,
    featured: false,
    customizable: true,
    variants: ['Option 1', 'Option 2', 'Option 3'],
    availability: 'made-to-order',
    keywords: ['beach', 'vibes', 'crochet', 'decor', 'beautiful', 'option'],
  },

  // ==================== BOUQUETS ====================
  {
    id: 'crochet-bouquet-custom',
    name: 'Crochet Bouquet',
    category: 'Bouquets',
    price: 0,
    description: 'A fully customizable crochet bouquet. Choose your flowers, colours and size. Price depends on your selections — discuss on WhatsApp for a quote.',
    shortDetail: 'Customizable — price on request',
    image: img.bouquet1,
    featured: true,
    customizable: true,
    variants: ['Roses', 'Tulips', 'Sunflowers', 'Mixed', 'Other'],
    availability: 'custom',
    keywords: ['crochet', 'bouquet', 'custom', 'customizable', 'flowers', 'gift'],
  },
  {
    id: 'tulip-spider-bouquet',
    name: 'Handmade Tulip Spider Bouquet',
    category: 'Bouquets',
    price: 500,
    originalPrice: 600,
    description: 'A beautiful handmade tulip spider crochet bouquet. Unique and eye-catching.',
    shortDetail: 'Tulip spider bouquet',
    image: img.bouquet2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['tulip', 'spider', 'bouquet', 'handmade', 'flower', 'crochet'],
  },
  {
    id: 'batman-bouquet',
    name: 'Crochet Batman Bouquet',
    category: 'Bouquets',
    price: 1800,
    originalPrice: 2000,
    description: 'A unique Batman-themed crochet bouquet. Perfect for superhero fans!',
    shortDetail: 'Batman themed bouquet',
    image: img.bouquet3,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'made-to-order',
    keywords: ['batman', 'bouquet', 'superhero', 'theme', 'crochet', 'gift'],
  },
  {
    id: 'crochet-bookmarks',
    name: 'Crochet Book Marks',
    category: 'Bouquets',
    price: 200,
    description: 'Beautiful handmade crochet bookmarks. Perfect for book lovers!',
    shortDetail: 'Crochet bookmark',
    image: img.flower4,
    featured: false,
    customizable: true,
    variants: ['Flower', 'Heart', 'Butterfly', 'Other'],
    availability: 'in-stock',
    keywords: ['bookmark', 'book', 'mark', 'crochet', 'reading', 'gift'],
  },

  // ==================== CHARACTER / SPECIAL PRODUCTS ====================
  {
    id: 'cute-krishna',
    name: 'Cute Krishna',
    category: 'Character & Cute Creations',
    price: 2500,
    originalPrice: 3000,
    description: 'A beautiful handmade crochet Krishna doll. Intricately crafted with love and devotion.',
    shortDetail: 'Handmade Krishna doll',
    image: img.amigurumi6,
    featured: true,
    customizable: false,
    variants: [],
    availability: 'made-to-order',
    keywords: ['krishna', 'god', 'doll', 'cute', 'handmade', 'crochet', 'amigurumi'],
  },
  {
    id: 'superman',
    name: 'Superman',
    category: 'Character & Cute Creations',
    price: 550,
    originalPrice: 600,
    description: 'A cute Superman crochet figure. Perfect for superhero fans!',
    shortDetail: 'Superman figure',
    image: img.amigurumi2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['superman', 'superhero', 'figure', 'cute', 'crochet', 'amigurumi'],
  },
  {
    id: 'batman-keychain',
    name: 'Batman Keychain',
    category: 'Character & Cute Creations',
    price: 550,
    originalPrice: 600,
    description: 'A Batman-design crochet keychain. Perfect for DC fans!',
    shortDetail: 'Batman keychain',
    image: img.keychain2,
    featured: false,
    customizable: false,
    variants: [],
    availability: 'in-stock',
    keywords: ['batman', 'keychain', 'superhero', 'dc', 'cute', 'crochet'],
  },
];

export const categories: CategoryInfo[] = [
  {
    name: 'Hair Accessories',
    slug: 'hair-accessories',
    description: 'Handmade crochet scrunchies, clips, pins, bands and clutcher clips',
    image: img.hairAccessory,
    icon: 'Sparkles',
  },
  {
    name: 'Keychains & Charms',
    slug: 'keychains-charms',
    description: 'Cute crochet keychains, alphabet charms and mini characters',
    image: img.keychain1,
    icon: 'Key',
  },
  {
    name: 'Crochet Flowers',
    slug: 'crochet-flowers',
    description: 'Beautiful handmade crochet flowers — tulips, sunflowers, lavender and more',
    image: img.flower1,
    icon: 'Flower2',
  },
  {
    name: 'Bouquets',
    slug: 'bouquets',
    description: 'Stunning crochet bouquets for gifting, weddings and special occasions',
    image: img.bouquet1,
    icon: 'Flower',
  },
  {
    name: 'Home & Car Décor',
    slug: 'home-car-decor',
    description: 'Crochet car hangings, curtains and decorative pieces for your space',
    image: img.decor1,
    icon: 'Home',
  },
  {
    name: 'Character & Cute Creations',
    slug: 'character-cute-creations',
    description: 'Cute amigurumi characters — Krishna, Superman, Batman and more',
    image: img.amigurumi2,
    icon: 'Heart',
  },
  {
    name: 'Customized Creations',
    slug: 'customized-creations',
    description: 'Your colour, your idea, your creation — fully personalized crochet items',
    image: img.yarn1,
    icon: 'Palette',
  },
  {
    name: 'Gifts',
    slug: 'gifts',
    description: 'Thoughtful handmade crochet gifts for every occasion',
    image: img.bouquet4,
    icon: 'Gift',
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getOnSaleProducts(): Product[] {
  return products.filter((p) => p.originalPrice && p.originalPrice > p.price);
}

export function getCustomizableProducts(): Product[] {
  return products.filter((p) => p.customizable);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase().trim();
  if (!q) return products;
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.keywords.some((k) => k.toLowerCase().includes(q)) ||
      p.description.toLowerCase().includes(q)
  );
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}
